### ISSUE TITLE
[BUG] 如何指定裁剪后的照片像素 / How to specify the pixels of a cropped photo

### ISSUE THREAD

**Issue by muxinxy** [aoguai/LiYing#1]
### 一些验证 / Some verifications

- [X] 是否查看 wiki、issues 后自己尝试解决 / Have you tried to resolve the issue by checking the wiki and existing issues?
- [X] 请 **确保** 您的问题能在 [releases](https://github.com/aoguai/LiYing/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题) / Please **ensure** your issue can be reproduced on the latest version (including test versions) released in [releases](https://github.com/aoguai/LiYing/releases/latest) (if not, please update to the latest version and reproduce the issue before submitting it)
- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题 / Search to check if there are already issues/discussions requesting the same feature to avoid duplication
- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题 / Acknowledge and agree that maintainers can directly close issues that do not follow the issue guidelines
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题 / Ensure to provide the following bug description and reproduction steps, otherwise, I agree that maintainers can directly close the issue

### BUG 描述或反馈描述 / Bug description or feedback description

如何指定裁剪后的照片像素，比如295x413、130x160等
如何指定压缩后的照片大小限制，比如500KB、200KB等

### 预期的效果 / Expected behavior

可以指定照片裁剪后的像素、压缩后的大小限制

### 截图 / Screenshots

![QQ截图20240804205108](https://github.com/user-attachments/assets/aee70614-8479-4610-974f-e9b0378adcd9)

### 系统信息 / System information

Windows 10

**Comment by aoguai** [comment]
你可以参考 [其他配置](https://github.com/aoguai/LiYing?tab=readme-ov-file#%E5%85%B6%E4%BB%96%E9%85%8D%E7%BD%AE) 中修改或添加自定义证件照配置，然后再使用对应的节名称调用使用即可。
